-- This project's schema is now tracked as incremental migrations in
-- supabase/migrations/, run in order:
--
--   001_initial_schema.sql            Cohorts + registrations (original schema)
--   002_payments_and_students.sql     Milestone 1: payments, students, storage bucket
--
-- Run each file's SQL in the Supabase SQL editor, in order. See
-- 002_payments_and_students.sql for a two-step run note specific
-- to that migration (Postgres enum-value restriction).
