import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendEnrollmentConfirmationEmail } from "@/lib/email/sendConfirmation";

export type EnrollmentSource = "paystack" | "bank_transfer_admin_approval";

interface FinalizeEnrollmentParams {
  paymentId: string;
  amountPaidNgn: number;
  source: EnrollmentSource;
  paystack?: { reference: string; transactionId: string };
  reviewedBy?: string; // admin email, when source is a manual approval
}

interface FinalizeEnrollmentResult {
  studentCode: string;
  onboardingUrl: string;
  accountSetupUrl: string | null;
  alreadyProcessed: boolean;
}

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://cohort.eloratechinstitute.com";

/**
 * Idempotent: if the payment is already `paid`, returns the existing
 * student without creating a duplicate or re-sending the email.
 */
export async function finalizeEnrollment(params: FinalizeEnrollmentParams): Promise<FinalizeEnrollmentResult> {
  const supabase = createAdminClient();

  const { data: payment, error: paymentError } = await supabase
    .from("payments")
    .select("*")
    .eq("id", params.paymentId)
    .single();

  if (paymentError || !payment) {
    throw new Error("Payment record not found.");
  }

  // Idempotency guard — Paystack webhooks can retry, and a student
  // might land on the callback page after the webhook already ran.
  if (payment.status === "paid") {
    const { data: existingStudent } = await supabase
      .from("students")
      .select("student_code")
      .eq("registration_id", payment.registration_id)
      .single();

    if (existingStudent) {
      return {
        studentCode: existingStudent.student_code,
        onboardingUrl: `${siteUrl}/onboarding/${existingStudent.student_code}`,
        accountSetupUrl: null, // duplicate call — no fresh email is sent on this path anyway
        alreadyProcessed: true,
      };
    }
    // Payment says paid but no student row exists yet (shouldn't normally
    // happen) — fall through and create one.
  }

  const { data: registration, error: registrationError } = await supabase
    .from("registrations")
    .select("*")
    .eq("id", payment.registration_id)
    .single();

  if (registrationError || !registration) {
    throw new Error("Registration not found for this payment.");
  }

  const { data: cohort, error: cohortError } = await supabase
    .from("cohorts")
    .select("*")
    .eq("id", payment.cohort_id)
    .single();

  if (cohortError || !cohort) {
    throw new Error("Cohort not found for this payment.");
  }

  // 1. Mark the payment paid.
  const { error: updatePaymentError } = await supabase
    .from("payments")
    .update({
      status: "paid",
      amount_paid: params.amountPaidNgn,
      payment_date: new Date().toISOString(),
      ...(params.paystack && {
        paystack_reference: params.paystack.reference,
        paystack_transaction_id: params.paystack.transactionId,
      }),
      ...(params.reviewedBy && {
        reviewed_by: params.reviewedBy,
        reviewed_at: new Date().toISOString(),
      }),
    })
    .eq("id", payment.id);

  if (updatePaymentError) {
    throw new Error(`Failed to update payment: ${updatePaymentError.message}`);
  }

  // 2. Mark the registration paid.
  await supabase.from("registrations").update({ status: "paid" }).eq("id", registration.id);

  // 3. Create the student record (student_code is auto-generated by trigger).
  //    Unique on registration_id, so a retry here is also safe.
  const { error: studentError } = await supabase
    .from("students")
    .upsert(
      {
        registration_id: registration.id,
        cohort_id: cohort.id,
        full_name: registration.full_name,
        email: registration.email,
        phone: registration.phone,
        status: "active",
      },
      { onConflict: "registration_id", ignoreDuplicates: true }
    );

  if (studentError) {
    throw new Error(`Failed to create student record: ${studentError.message}`);
  }

  // upsert with ignoreDuplicates doesn't return the row either way (new or
  // pre-existing) — fetch it fresh so we have both the code and the id.
  const { data: studentRow } = await supabase
    .from("students")
    .select("id, student_code, auth_user_id")
    .eq("registration_id", registration.id)
    .single();

  if (!studentRow) {
    throw new Error("Failed to create or find the student record.");
  }
  const studentCode = studentRow.student_code;

  const onboardingUrl = `${siteUrl}/onboarding/${studentCode}`;

  // 4. Create the student's login account and a one-time link to set
  //    their password. Best-effort: enrollment must not fail just
  //    because account provisioning hiccups — the student can still
  //    reach the onboarding page, and this can be retried later.
  const accountSetupUrl = await provisionStudentAccount({
    studentRowId: studentRow.id,
    existingAuthUserId: studentRow.auth_user_id,
    email: registration.email,
  });

  // 5. Best-effort confirmation email — never blocks or fails enrollment.
  await sendEnrollmentConfirmationEmail({
    to: registration.email,
    fullName: registration.full_name,
    studentCode,
    onboardingUrl,
    accountSetupUrl,
    cohortName: cohort.name,
    startsOn: cohort.starts_on,
    durationWeeks: cohort.duration_weeks,
  });

  return { studentCode, onboardingUrl, accountSetupUrl, alreadyProcessed: false };
}

/**
 * Ensures the student has a Supabase Auth account, then returns a
 * one-time link they can use to set their password. Best-effort:
 * returns null (rather than throwing) on any failure, since a
 * missing account-setup link should never break enrollment — the
 * student still has the onboarding page and can be re-linked later.
 */
async function provisionStudentAccount(params: {
  studentRowId: string;
  existingAuthUserId: string | null;
  email: string;
}): Promise<string | null> {
  const supabase = createAdminClient();
  const redirectTo = `${siteUrl}/account/setup`;

  try {
    let authUserId = params.existingAuthUserId;

    if (!authUserId) {
      const { data: created, error: createError } = await supabase.auth.admin.createUser({
        email: params.email,
        email_confirm: true, // we send our own custom email — no need for Supabase's confirmation email
      });

      if (createError || !created.user) {
        // Most likely cause: an auth user with this email already exists
        // (e.g. re-enrollment under the same email). Look it up instead
        // of failing account provisioning outright.
        const { data: existingUsers } = await supabase.auth.admin.listUsers();
        const match = existingUsers?.users.find((u) => u.email?.toLowerCase() === params.email.toLowerCase());
        if (!match) {
          console.error("provisionStudentAccount: could not create or find auth user for", params.email, createError);
          return null;
        }
        authUserId = match.id;
      } else {
        authUserId = created.user.id;
      }

      await supabase.from("students").update({ auth_user_id: authUserId }).eq("id", params.studentRowId);
    }

    const { data: link, error: linkError } = await supabase.auth.admin.generateLink({
      type: "recovery",
      email: params.email,
      options: { redirectTo },
    });

    if (linkError || !link?.properties?.hashed_token) {
      console.error("provisionStudentAccount: could not generate setup link for", params.email, linkError);
      return null;
    }

    // Send our own link with the raw token_hash rather than Supabase's
    // action_link. action_link auto-verifies on GET, which gets silently
    // consumed by email providers' automatic link-safety scanners before
    // the student ever clicks it. token_hash is only verified client-side
    // via an explicit user action on /account/setup (see that page).
    return `${redirectTo}?token_hash=${encodeURIComponent(link.properties.hashed_token)}&type=recovery`;
  } catch (err) {
    console.error("provisionStudentAccount failed:", err);
    return null;
  }
}
