import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendEnrollmentConfirmationEmail } from "@/lib/email/sendConfirmation";

export type EnrollmentSource = "paystack" | "bank_transfer_admin_approval";

interface FinalizeEnrollmentParams {
  paymentId: string;
  amountPaidNgn: number;
  source: EnrollmentSource;
  paystack?: { reference: string; transactionId: string };
  reviewedBy?: string; // admin email, when source is a manual approval
}

interface FinalizeEnrollmentResult {
  studentCode: string;
  onboardingUrl: string;
  alreadyProcessed: boolean;
}

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://eloratechinstitute.com";

/**
 * Idempotent: if the payment is already `paid`, returns the existing
 * student without creating a duplicate or re-sending the email.
 */
export async function finalizeEnrollment(params: FinalizeEnrollmentParams): Promise<FinalizeEnrollmentResult> {
  const supabase = createAdminClient();

  const { data: payment, error: paymentError } = await supabase
    .from("payments")
    .select("*")
    .eq("id", params.paymentId)
    .single();

  if (paymentError || !payment) {
    throw new Error("Payment record not found.");
  }

  // Idempotency guard — Paystack webhooks can retry, and a student
  // might land on the callback page after the webhook already ran.
  if (payment.status === "paid") {
    const { data: existingStudent } = await supabase
      .from("students")
      .select("student_code")
      .eq("registration_id", payment.registration_id)
      .single();

    if (existingStudent) {
      return {
        studentCode: existingStudent.student_code,
        onboardingUrl: `${siteUrl}/onboarding/${existingStudent.student_code}`,
        alreadyProcessed: true,
      };
    }
    // Payment says paid but no student row exists yet (shouldn't normally
    // happen) — fall through and create one.
  }

  const { data: registration, error: registrationError } = await supabase
    .from("registrations")
    .select("*")
    .eq("id", payment.registration_id)
    .single();

  if (registrationError || !registration) {
    throw new Error("Registration not found for this payment.");
  }

  const { data: cohort, error: cohortError } = await supabase
    .from("cohorts")
    .select("*")
    .eq("id", payment.cohort_id)
    .single();

  if (cohortError || !cohort) {
    throw new Error("Cohort not found for this payment.");
  }

  // 1. Mark the payment paid.
  const { error: updatePaymentError } = await supabase
    .from("payments")
    .update({
      status: "paid",
      amount_paid: params.amountPaidNgn,
      payment_date: new Date().toISOString(),
      ...(params.paystack && {
        paystack_reference: params.paystack.reference,
        paystack_transaction_id: params.paystack.transactionId,
      }),
      ...(params.reviewedBy && {
        reviewed_by: params.reviewedBy,
        reviewed_at: new Date().toISOString(),
      }),
    })
    .eq("id", payment.id);

  if (updatePaymentError) {
    throw new Error(`Failed to update payment: ${updatePaymentError.message}`);
  }

  // 2. Mark the registration paid.
  await supabase.from("registrations").update({ status: "paid" }).eq("id", registration.id);

  // 3. Create the student record (student_code is auto-generated by trigger).
  //    Unique on registration_id, so a retry here is also safe.
  const { data: student, error: studentError } = await supabase
    .from("students")
    .upsert(
      {
        registration_id: registration.id,
        cohort_id: cohort.id,
        full_name: registration.full_name,
        email: registration.email,
        phone: registration.phone,
        status: "active",
      },
      { onConflict: "registration_id", ignoreDuplicates: true }
    )
    .select("student_code")
    .single();

  let studentCode = student?.student_code;
  if (studentError || !studentCode) {
    // upsert with ignoreDuplicates doesn't return the existing row — fetch it.
    const { data: existing } = await supabase
      .from("students")
      .select("student_code")
      .eq("registration_id", registration.id)
      .single();
    studentCode = existing?.student_code;
  }

  if (!studentCode) {
    throw new Error("Failed to create or find the student record.");
  }

  const onboardingUrl = `${siteUrl}/onboarding/${studentCode}`;

  // 4. Best-effort confirmation email — never blocks or fails enrollment.
  await sendEnrollmentConfirmationEmail({
    to: registration.email,
    fullName: registration.full_name,
    studentCode,
    onboardingUrl,
    cohortName: cohort.name,
    startsOn: cohort.starts_on,
    durationWeeks: cohort.duration_weeks,
  });

  return { studentCode, onboardingUrl, alreadyProcessed: false };
}
