-- ============================================================
-- Elora Tech Institute — Milestone 4 Phase 4C: Teaching &
-- Instructor Delivery System.
--
-- Seeds the September 2026 Web Development curriculum: 7 weeks,
-- 28 classes, transcribed directly from ETI's existing
-- 'September 2026 Web Development Cohort — Instructor Teaching
-- Guide & 28-Class Delivery Plan' source document — not invented
-- content. Where that document didn't state an explicit learning
-- objective for a class (most classes past Class 4), the outcome
-- below is a one-sentence summary of that same class's own listed
-- Topics/Practice/Deliverable — no new topics introduced beyond
-- what the source already lists for that class.
-- ============================================================

insert into curricula (code, name, description, is_active)
values (
  'WD-2026-09',
  'Web Development Cohort — September 2026',
  'HTML, CSS, JavaScript, APIs, Debugging, AI-Assisted Development, Deployment. 7 weeks, 28 classes, 6 shipped projects.',
  true
)
on conflict (code) do nothing;

insert into curriculum_classes
  (curriculum_id, class_number, week_number, week_theme, title, outcome, teaching_points, demo, practice, questions, assignment, checkpoint)
select
  c.id, v.class_number, v.week_number, v.week_theme, v.title, v.outcome,
  v.teaching_points, v.demo, v.practice, v.questions, v.assignment, v.checkpoint
from curricula c
cross join (
  values
    (1, 1, 'HTML Fundamentals', 'How the Web Works + HTML Foundations', 'Understand what a website is, the roles of the browser, server, URL, HTML, CSS, and JavaScript, and create a basic HTML document using elements, tags, and attributes.', '["How websites work", "Browser", "Server", "URL", "HTML", "CSS", "JavaScript", "HTML document structure", "<!DOCTYPE html>", "html", "head", "body", "Headings", "Paragraphs", "Links", "Images"]'::jsonb, '["Start with a real website. Ask: \"When you type a website address into your browser, what do you think happens?\" Use the answers to introduce the basic web-development mental model.", "Create an empty index.html file. Build the document from scratch. Explain each major piece rather than simply typing it."]'::jsonb, '["Students create a simple personal introduction page containing: their name, a short introduction, an image, a list of interests, a link, a page title."]'::jsonb, '["What is HTML responsible for?", "What is an element?", "What is an attribute?", "What belongs inside the head?", "What belongs inside the body?", "What happens when you change the HTML?"]'::jsonb, 'A simple personal introduction webpage.', 'Student has produced a simple personal introduction webpage.'),
    (2, 1, 'HTML Fundamentals', 'Semantic HTML', 'Students can structure a real website using semantic HTML.', '["Headings", "Paragraphs", "Links", "Images", "Lists", "header", "nav", "main", "section", "article", "footer", "Semantic structure"]'::jsonb, '["Create the structure of a local business website.", "Explain why the page should not simply be div \u2192 div \u2192 div \u2192 div.", "Show how semantic elements communicate meaning."]'::jsonb, '["Students create the HTML structure for: Header, Navigation, Hero, About, Services, Contact, Footer."]'::jsonb, '["Why use main?", "What belongs in nav?", "What makes an element semantic?", "When would you use article?", "Why is meaningful structure important?"]'::jsonb, 'Semantic HTML structure for Project 1.', 'Student has produced the semantic HTML structure for Project 1.'),
    (3, 1, 'HTML Fundamentals', 'Forms & Accessibility Basics', 'Students can create basic forms and understand foundational accessibility practices.', '["form", "label", "input", "textarea", "select", "button", "Input types", "required", "Accessibility", "Labels"]'::jsonb, '["Build a contact form showing Name, Email, Message, Submit button.", "Explain why labels matter.", "Explain why placeholder text is not a replacement for a proper label."]'::jsonb, '["Add a contact/booking form to the Business Website."]'::jsonb, '["Why do inputs need labels?", "What does required do?", "Which input type should be used for email?", "Why shouldn''t placeholder text replace labels?"]'::jsonb, 'Functional-looking, semantically structured contact form.', 'Student has a functional-looking, semantically structured contact form.'),
    (4, 1, 'HTML Fundamentals', 'PROJECT 1: Local Business Website', 'Students create their first complete real-world website structure.', '["Required sections: Header, Navigation, Hero, About, Services, Contact, Footer"]'::jsonb, '["Instructor should not build the student''s entire website for them. Instead: plan the structure, demonstrate one section, let students implement the rest, review common mistakes, help students debug."]'::jsonb, '["Students implement the remaining required sections themselves after the instructor demonstrates one section."]'::jsonb, '[]'::jsonb, 'Complete Project 1: Local Business Website.', 'Proper HTML structure, semantic elements, navigation, multiple sections, contact form, clean indentation, meaningful content.'),
    (5, 2, 'CSS & Responsive Design', 'CSS Fundamentals', 'Students can look at a CSS rule and explain its selector, property, and value, and apply CSS fundamentals to Project 1.', '["CSS syntax", "Selectors", "Classes", "IDs", "Colors", "Backgrounds", "Typography", "Borders", "External stylesheets"]'::jsonb, '[]'::jsonb, '["Style Project 1. Students should create: color hierarchy, typography hierarchy, styled buttons, section backgrounds, basic spacing."]'::jsonb, '["Given a CSS rule, identify the selector, property, and value."]'::jsonb, 'Styled version of Project 1.', 'Project 1 has a color hierarchy, typography hierarchy, styled buttons, section backgrounds, and basic spacing.'),
    (6, 2, 'CSS & Responsive Design', 'The CSS Box Model', 'Students stop solving every spacing problem by randomly adding margins and instead understand the box model.', '["Content", "Padding", "Border", "Margin", "Width", "Height", "box-sizing"]'::jsonb, '["Use browser DevTools. Show the box model visually. Create a deliberately broken layout and ask students to diagnose it."]'::jsonb, '["Students improve: section spacing, cards, buttons, containers, forms."]'::jsonb, '[]'::jsonb, 'Improved spacing across sections, cards, buttons, containers, and forms.', 'Students stop solving spacing problems by randomly adding margins.'),
    (7, 2, 'CSS & Responsive Design', 'Responsive Units & Media Queries', 'Students make Project 1 responsive and can identify obvious responsive-design problems across devices.', '["px", "%", "rem", "em", "vw", "vh", "Media queries", "Breakpoints", "Mobile-first thinking"]'::jsonb, '[]'::jsonb, '["Students make Project 1 responsive. Testing: desktop, tablet, mobile."]'::jsonb, '["Can you identify obvious overflow, tiny text, horizontal scrolling, broken navigation, or oversized images?"]'::jsonb, 'Responsive version of Project 1, tested on desktop, tablet, and mobile.', 'Project 1 is responsive with no obvious overflow, tiny text, horizontal scrolling, broken navigation, or oversized images.'),
    (8, 2, 'CSS & Responsive Design', 'PROJECT 2: Restaurant Website', 'Students build a coherent restaurant website that works at different screen sizes, applying HTML, CSS, typography, spacing, and responsive design.', '["Required sections: Hero, About, Menu, Gallery, Contact/location, Footer"]'::jsonb, '[]'::jsonb, '["Students apply HTML, CSS, typography, spacing, and responsive design skills to build the Restaurant Website."]'::jsonb, '[]'::jsonb, 'Complete Project 2: Restaurant Website.', 'A coherent restaurant website that works at different screen sizes.'),
    (9, 3, 'Flexbox & Grid', 'Flexbox Fundamentals', 'Students can build layouts using Flexbox — flex containers, main/cross axis, and alignment/spacing properties.', '["Flex container", "Main axis", "Cross axis", "flex-direction", "justify-content", "align-items", "gap", "flex-wrap"]'::jsonb, '["Build: navigation, card row, button group."]'::jsonb, '["Students refactor sections of the Restaurant Website."]'::jsonb, '[]'::jsonb, 'Refactored sections of the Restaurant Website using Flexbox.', 'Navigation, card row, and button group sections rebuilt with Flexbox.'),
    (10, 3, 'Flexbox & Grid', 'Real Flexbox Layouts & Debugging', 'Students learn to inspect a broken layout instead of randomly changing properties, applying Flexbox to real layout problems.', '["Hero layouts", "Cards", "Navigation", "Flexible sizing", "Overflow", "Alignment problems"]'::jsonb, '[]'::jsonb, '["Students improve: Restaurant hero, menu cards, navigation."]'::jsonb, '[]'::jsonb, 'Improved Restaurant hero, menu cards, and navigation.', 'Students inspect broken layouts systematically rather than randomly changing properties.'),
    (11, 3, 'Flexbox & Grid', 'CSS Grid', 'Students understand rows, columns, and responsive grids, and can reason about when to choose Grid vs Flexbox.', '["Rows", "Columns", "grid-template-columns", "gap", "repeat", "Responsive grids", "Grid vs Flexbox"]'::jsonb, '[]'::jsonb, '["Build: gallery, product cards, multi-column section."]'::jsonb, '["Would you choose Flexbox or Grid for this layout, and why? (Understanding the reasoning matters more than memorizing the answer.)"]'::jsonb, 'Gallery, product cards, and a multi-column section built with CSS Grid.', 'Students can explain their Grid vs Flexbox choice with reasoning, not just recall.'),
    (12, 3, 'Flexbox & Grid', 'PROJECT 3: Product Launch Landing Page', 'Students build a complete responsive product landing page applying Flexbox, Grid, responsive design, visual hierarchy, spacing, and component-style thinking.', '["Required sections: Hero, Features, Benefits, Pricing or offer, Testimonials, CTA, Footer"]'::jsonb, '[]'::jsonb, '["Students apply Flexbox, Grid, responsive design, visual hierarchy, spacing, and component-style thinking to build the landing page."]'::jsonb, '[]'::jsonb, 'Complete Project 3: Product Launch Landing Page.', 'A complete responsive product landing page.'),
    (13, 4, 'JavaScript Basics', 'JavaScript Foundations', 'Students can explain what values are stored in different variables using let, const, strings, numbers, and booleans.', '["What JavaScript does", "Variables", "let", "const", "Strings", "Numbers", "Booleans", "Console"]'::jsonb, '[]'::jsonb, '["Small programming exercises."]'::jsonb, '["What values are stored in different variables?"]'::jsonb, 'Small programming exercises covering variables and basic data types.', 'Students can explain what value is stored in a given variable.'),
    (14, 4, 'JavaScript Basics', 'Operators & Control Flow', 'Students can build small decision-making programs using arithmetic, comparison, and logical operators with if/else/else if.', '["Arithmetic", "Comparison", "Logical operators", "if", "else", "else if"]'::jsonb, '[]'::jsonb, '["Build small decision-making programs. Examples: age checker, price calculator, login condition, eligibility checker."]'::jsonb, '[]'::jsonb, 'A small decision-making program (e.g. age checker, price calculator, login condition, or eligibility checker).', 'Student has a working decision-making program using conditionals.'),
    (15, 4, 'JavaScript Basics', 'Functions', 'Students can create reusable functions using parameters and return values.', '["Function declaration", "Parameters", "Arguments", "Return values", "Scope", "Reusable logic"]'::jsonb, '[]'::jsonb, '["Students create utility functions."]'::jsonb, '["What goes into the function, what happens inside it, and what comes out?"]'::jsonb, 'A set of reusable utility functions.', 'Student can explain what goes into a function, what happens inside it, and what comes out.'),
    (16, 4, 'JavaScript Basics', 'PROJECT 4: Interactive JS App Foundations', 'Students create the application''s data and logic foundation (arrays, objects, state) before connecting everything to the DOM.', '["Arrays", "Objects", "Application data", "State", "Planning application logic"]'::jsonb, '[]'::jsonb, '["Project options (standardized by ETI or selected from approved options): to-do app, expense tracker, quiz app, calculator, habit tracker."]'::jsonb, '[]'::jsonb, 'Application data and logic foundation for the chosen Interactive JS App, before DOM integration.', 'Application data and logic foundation is complete and ready to connect to the DOM.'),
    (17, 5, 'DOM Manipulation & APIs', 'DOM Fundamentals', 'Students can select, read, create, and remove DOM elements to connect their app''s data to the webpage.', '["DOM", "querySelector", "querySelectorAll", "textContent", "Classes", "Creating elements", "Removing elements"]'::jsonb, '[]'::jsonb, '["Connect the Interactive JS App''s data to the webpage."]'::jsonb, '[]'::jsonb, 'Interactive JS App with its data connected to the DOM.', 'The app''s data renders on the webpage via DOM manipulation.'),
    (18, 5, 'DOM Manipulation & APIs', 'Events & User Interaction', 'Students internalize the mental model: user action → event → logic → state change → UI update.', '["Event listeners", "click", "submit", "input", "Event object", "preventDefault"]'::jsonb, '["Teach students to think: User action \u2192 Event \u2192 Logic \u2192 State change \u2192 UI update. This mental model is extremely important."]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'App updated to respond to user events (click, submit, input).', 'Student can articulate the user action → event → logic → state change → UI update flow for their app.'),
    (19, 5, 'DOM Manipulation & APIs', 'Forms, Validation & State', 'Students produce a functional Interactive JavaScript App with form handling, validation, and state updates.', '["Form handling", "Validation", "State updates", "Arrays/objects", "Rendering updated state", "Empty states", "Error messages"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'Functional Interactive JavaScript App.', 'App has working form handling, validation, and state-driven rendering, including empty and error states.'),
    (20, 5, 'DOM Manipulation & APIs', 'APIs & Weather App', 'Students successfully retrieve weather data from a real API.', '["What an API is", "Endpoint", "Request", "Response", "JSON", "fetch", "async/await", "API documentation", "API keys"]'::jsonb, '["Make a real API request. Show students the raw response. Then identify the useful data."]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'Successful retrieval of weather data from a real API.', 'Student successfully retrieves weather data from the API.'),
    (21, 6, 'Debugging & AI', 'Weather App: Rendering Real Data', 'Students produce a functional Weather App that reads API responses, extracts data, and renders it into the DOM with loading and error states.', '["Reading API responses", "Extracting data", "Rendering into DOM", "Loading state", "Error state"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'Functional Weather App.', 'Weather App renders real API data with working loading and error states.'),
    (22, 6, 'Debugging & AI', 'Debugging Like a Developer', 'Students learn to troubleshoot independently by reproducing bugs, isolating problems, and testing fixes.', '["Syntax errors", "Runtime errors", "Logic errors", "Network errors", "Console", "DevTools", "Reproducing bugs", "Isolating problems", "Testing fixes"]'::jsonb, '["Give students broken code deliberately. Do not immediately fix it. Ask: What happened? What did you expect? What does the error say? Where does the error occur? What can we test? Did the fix actually solve the problem?"]'::jsonb, '["Students work through deliberately broken code using the debugging questions above."]'::jsonb, '["What happened?", "What did you expect?", "What does the error say?", "Where does the error occur?", "What can we test?", "Did the fix actually solve the problem?"]'::jsonb, 'Debugged version of the deliberately broken code provided in class.', 'Student can reproduce, isolate, and verify the fix for a bug using the debugging process taught.'),
    (23, 6, 'Debugging & AI', 'AI-Assisted Development', 'Students learn to use AI tools responsibly to reason about code rather than outsourcing the entire assignment to AI.', '["Tools: ChatGPT, Claude, DeepSeek", "Using AI for: explaining code, generating small features, brainstorming approaches, debugging, refactoring, documentation, learning unfamiliar concepts", "Do NOT teach: \"Give AI the entire assignment and paste whatever it gives you.\" Instead teach: \"Give AI enough context to help you reason.\"", "Prompt structure: goal, relevant code, expected behavior, actual behavior, error message, constraints"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'Practice writing a well-structured AI prompt (goal, relevant code, expected behavior, actual behavior, error message, constraints) against a real problem in your project.', 'Student can write a well-structured AI prompt containing goal, relevant code, expected behavior, actual behavior, error message, and constraints.'),
    (24, 6, 'Debugging & AI', 'AI Debugging & Code Review', 'Students use AI as a second pair of eyes and can explain every AI-generated change they keep.', '["Using AI for debugging and code review"]'::jsonb, '[]'::jsonb, '["Give AI a broken function. Ask it to identify the likely issue. Verify its explanation. Apply the fix. Test it. Ask AI for a code review. Decide which suggestions are actually useful."]'::jsonb, '[]'::jsonb, 'Give AI a broken function from your project, verify its explanation, apply and test the fix, then request a code review and note which suggestions were actually useful.', 'Student can explain every AI-generated change they kept.'),
    (25, 7, 'Build & Ship', 'PROJECT 6: Personal Portfolio Website', 'Students build a portfolio that showcases their previous five projects rather than inventing fake projects.', '["Required sections: About, Skills, Projects, Project descriptions, Contact, Relevant links"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'Complete Project 6: Personal Portfolio Website, showcasing the previous five projects.', 'Portfolio showcases the student''s actual previous five projects, not invented ones.'),
    (26, 7, 'Build & Ship', 'Final Build', 'Every student knows what they are building, what remains, what the priority is, and what must be completed before deployment.', '["Reviewing scope", "Preventing overbuilding", "Prioritization", "Asking questions before providing solutions", "Reviewing AI-generated changes", "Debugging support"]'::jsonb, '[]'::jsonb, '["Students choose a project to substantially improve or complete."]'::jsonb, '["What are you building?", "What remains?", "What is the priority?", "What must be completed before deployment?"]'::jsonb, 'Substantially improved or completed project of the student''s choice.', 'Student can state what they''re building, what remains, the priority, and what must be done before deployment.'),
    (27, 7, 'Build & Ship', 'Polish, Debug & Deploy', 'Students verify their deployed project works, not just their local version.', '["Responsive testing", "Mobile testing", "Desktop testing", "Broken links", "Console errors", "Form behavior", "Accessibility basics", "Code cleanup", "Git/GitHub", "Deployment", "Live URL verification"]'::jsonb, '[]'::jsonb, '["Students work through the polish/debug/deploy checklist and verify the live deployed URL, not just the local version."]'::jsonb, '[]'::jsonb, 'Deployed, verified live project.', 'Live deployed URL has been tested and verified — the project is not considered done just because it works locally.'),
    (28, 7, 'Build & Ship', 'Showcase & Technical Defense', 'Every student can explain what they built, the problem it solves, how they structured it, and how they used and verified AI-generated code.', '["Student presentations of their work"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '["What did you build?", "What problem does it solve?", "How did you structure it?", "What was difficult?", "What bug gave you the most trouble?", "How did you solve it?", "Where did you use AI?", "What did AI get wrong?", "How did you verify AI-generated code?", "What would you improve next?"]'::jsonb, 'Course complete — no further assignment.', 'Student can answer all technical defense questions about their own work — the goal is to verify understanding, not to embarrass students.')
) as v(class_number, week_number, week_theme, title, outcome, teaching_points, demo, practice, questions, assignment, checkpoint)
where c.code = 'WD-2026-09'
on conflict (curriculum_id, class_number) do nothing;

-- Link the existing seeded September 2026 cohort (001_initial_schema.sql)
-- to this curriculum, if that cohort still exists under its original name.
update cohorts
set curriculum_id = (select id from curricula where code = 'WD-2026-09')
where name = 'Web Development Cohort' and curriculum_id is null;
